# Generated by Django 5.2.6 on 2025-10-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='image_url',
            new_name='design_url',
        ),
        migrations.AddField(
            model_name='design',
            name='mockup_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='design',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
